# Generated by Django 5.2.6 on 2026-04-13 15:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('READY', 'Ready'), ('SENT', 'Sent'), ('ERROR', 'Error'), ('RETRY_PENDING', 'Retry pending')], default='READY', max_length=32)),
                ('destination', models.CharField(default='csv', max_length=64)),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('inn', models.CharField(blank=True, default='', max_length=16)),
                ('kpp', models.CharField(blank=True, default='', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='invoices_co_name_525859_idx'), models.Index(fields=['inn'], name='invoices_co_inn_1237ed_idx')],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('mnemonic', models.CharField(max_length=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['code'], name='invoices_de_code_8b56c8_idx'), models.Index(fields=['name'], name='invoices_de_name_9a03d6_idx')],
            },
        ),
        migrations.CreateModel(
            name='AggregationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drf', models.CharField(max_length=64, unique=True)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('READY', 'Ready'), ('DRAFT', 'Draft built'), ('VALIDATION_ERROR', 'Validation error'), ('MATERIALIZED', 'Materialized')], default='OPEN', max_length=32)),
                ('income_count', models.PositiveIntegerField(default=0)),
                ('vat_count', models.PositiveIntegerField(default=0)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('validation_error', models.TextField(blank=True, default='')),
                ('last_processed_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aggregation_groups', to='invoices.counterparty')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aggregation_groups', to='invoices.department')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, default='', max_length=64)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to='invoices.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_access', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DraftInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('vat_rate', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=6)),
                ('total_vat_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('total_with_vat', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready'), ('VALIDATION_ERROR', 'Validation error'), ('MATERIALIZED', 'Materialized'), ('MATERIALIZATION_ERROR', 'Materialization error')], default='DRAFT', max_length=32)),
                ('validation_error', models.TextField(blank=True, default='')),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('materialized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draft_invoices', to='invoices.counterparty')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draft_invoices', to='invoices.department')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft_invoice', to='invoices.aggregationgroup')),
            ],
        ),
        migrations.CreateModel(
            name='ExportAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_no', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('ERROR', 'Error')], max_length=16)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('export_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='invoices.exportrecord')),
            ],
        ),
        migrations.CreateModel(
            name='FinalInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=64, unique=True)),
                ('drf', models.CharField(max_length=64)),
                ('transaction_date', models.DateField()),
                ('vat_rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('total_vat_amount', models.DecimalField(decimal_places=4, max_digits=16)),
                ('total_with_vat', models.DecimalField(decimal_places=4, max_digits=16)),
                ('status', models.CharField(choices=[('MATERIALIZED', 'Materialized'), ('EXPORT_READY', 'Export ready'), ('EXPORT_ERROR', 'Export error'), ('RETRY_PENDING', 'Retry pending')], default='MATERIALIZED', max_length=32)),
                ('export_status', models.CharField(choices=[('MATERIALIZED', 'Materialized'), ('EXPORT_READY', 'Export ready'), ('EXPORT_ERROR', 'Export error'), ('RETRY_PENDING', 'Retry pending')], default='EXPORT_READY', max_length=32)),
                ('materialized_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='final_invoices', to='invoices.counterparty')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='final_invoices', to='invoices.department')),
                ('draft_invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_invoice', to='invoices.draftinvoice')),
            ],
        ),
        migrations.AddField(
            model_name='exportrecord',
            name='final_invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='export_record', to='invoices.finalinvoice'),
        ),
        migrations.CreateModel(
            name='FinalInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=32)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=16)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=16)),
                ('amount_without_vat', models.DecimalField(decimal_places=4, max_digits=16)),
                ('vat_amount', models.DecimalField(decimal_places=4, max_digits=16)),
                ('total_amount', models.DecimalField(decimal_places=4, max_digits=16)),
                ('final_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoices.finalinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='InboundMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(blank=True, default='', max_length=64)),
                ('drf', models.CharField(blank=True, default='', max_length=64)),
                ('source', models.CharField(choices=[('API', 'API'), ('SCRIPT', 'Script'), ('RABBIT_DIRECT', 'Rabbit direct')], default='API', max_length=32)),
                ('payload_hash', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PUBLISHED', 'Published'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('VALIDATION_ERROR', 'Validation error'), ('DUPLICATE', 'Duplicate'), ('ERROR', 'Error')], default='RECEIVED', max_length=32)),
                ('error_message', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['drf'], name='invoices_in_drf_4f1a7f_idx'), models.Index(fields=['status'], name='invoices_in_status_d51cea_idx'), models.Index(fields=['received_at'], name='invoices_in_receive_4a1a75_idx'), models.Index(fields=['payload_hash'], name='invoices_in_payload_7d646b_idx')],
            },
        ),
        migrations.CreateModel(
            name='InvoiceFieldChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=128)),
                ('old_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_field_changes', to=settings.AUTH_USER_MODEL)),
                ('final_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_history', to='invoices.finalinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_date', models.DateField()),
                ('version', models.CharField(default='00', max_length=2)),
                ('last_value', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_sequences', to='invoices.department')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, default='', max_length=32)),
                ('to_status', models.CharField(max_length=32)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_status_changes', to=settings.AUTH_USER_MODEL)),
                ('final_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='invoices.finalinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='MaterializationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('ERROR', 'Error'), ('RETRY', 'Retry')], default='PENDING', max_length=16)),
                ('attempt', models.PositiveIntegerField(default=1)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draft_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materialization_jobs', to='invoices.draftinvoice')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materialization_jobs', to='invoices.aggregationgroup')),
            ],
        ),
        migrations.CreateModel(
            name='RawTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, default='', max_length=128)),
                ('drf', models.CharField(max_length=64)),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Income'), ('VAT', 'VAT')], max_length=16)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('product_name', models.CharField(blank=True, default='', max_length=255)),
                ('unit_measure', models.CharField(blank=True, default='', max_length=32)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('vat_rate', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=6)),
                ('vat_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('payload_hash', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('VALIDATION_ERROR', 'Validation error'), ('DUPLICATE', 'Duplicate'), ('PROCESSED', 'Processed')], default='RECEIVED', max_length=32)),
                ('validation_error', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aggregation_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_transactions', to='invoices.aggregationgroup')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='raw_transactions', to='invoices.counterparty')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='raw_transactions', to='invoices.department')),
                ('inbound_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_transactions', to='invoices.inboundmessagelog')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('INGEST', 'Ingest'), ('PROCESSOR', 'Processor'), ('AGGREGATION', 'Aggregation'), ('MATERIALIZATION', 'Materialization'), ('EXPORT', 'Export')], max_length=32)),
                ('code', models.CharField(max_length=64)),
                ('message', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('retryable', models.BooleanField(default=True)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aggregation_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_errors', to='invoices.aggregationgroup')),
                ('draft_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_errors', to='invoices.draftinvoice')),
                ('final_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_errors', to='invoices.finalinvoice')),
                ('raw_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_errors', to='invoices.rawtransaction')),
            ],
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload_hash', models.CharField(max_length=64, unique=True)),
                ('drf', models.CharField(blank=True, default='', max_length=64)),
                ('source', models.CharField(blank=True, default='', max_length=32)),
                ('times_seen', models.PositiveIntegerField(default=1)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('inbound_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idempotency_records', to='invoices.inboundmessagelog')),
                ('raw_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idempotency_records', to='invoices.rawtransaction')),
            ],
        ),
        migrations.CreateModel(
            name='DraftInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=32)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=16)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=16)),
                ('amount_without_vat', models.DecimalField(decimal_places=4, max_digits=16)),
                ('vat_amount', models.DecimalField(decimal_places=4, max_digits=16)),
                ('total_amount', models.DecimalField(decimal_places=4, max_digits=16)),
                ('draft_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoices.draftinvoice')),
                ('raw_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_lines', to='invoices.rawtransaction')),
            ],
        ),
        migrations.AddIndex(
            model_name='aggregationgroup',
            index=models.Index(fields=['drf'], name='invoices_ag_drf_b763de_idx'),
        ),
        migrations.AddIndex(
            model_name='aggregationgroup',
            index=models.Index(fields=['status'], name='invoices_ag_status_196f82_idx'),
        ),
        migrations.AddIndex(
            model_name='aggregationgroup',
            index=models.Index(fields=['transaction_date'], name='invoices_ag_transac_e0fca1_idx'),
        ),
        migrations.AddIndex(
            model_name='aggregationgroup',
            index=models.Index(fields=['created_at'], name='invoices_ag_created_84507b_idx'),
        ),
        migrations.AddIndex(
            model_name='aggregationgroup',
            index=models.Index(fields=['updated_at'], name='invoices_ag_updated_7b7c25_idx'),
        ),
        migrations.AddIndex(
            model_name='aggregationgroup',
            index=models.Index(fields=['counterparty'], name='invoices_ag_counter_63bbd1_idx'),
        ),
        migrations.AddIndex(
            model_name='aggregationgroup',
            index=models.Index(fields=['department'], name='invoices_ag_departm_57e035_idx'),
        ),
        migrations.AddConstraint(
            model_name='departmentaccess',
            constraint=models.UniqueConstraint(fields=('user', 'department'), name='uniq_department_access'),
        ),
        migrations.AddIndex(
            model_name='draftinvoice',
            index=models.Index(fields=['status'], name='invoices_dr_status_5cdae2_idx'),
        ),
        migrations.AddIndex(
            model_name='draftinvoice',
            index=models.Index(fields=['transaction_date'], name='invoices_dr_transac_592e33_idx'),
        ),
        migrations.AddIndex(
            model_name='draftinvoice',
            index=models.Index(fields=['created_at'], name='invoices_dr_created_e6427b_idx'),
        ),
        migrations.AddIndex(
            model_name='draftinvoice',
            index=models.Index(fields=['department'], name='invoices_dr_departm_8bbdae_idx'),
        ),
        migrations.AddIndex(
            model_name='draftinvoice',
            index=models.Index(fields=['counterparty'], name='invoices_dr_counter_6c675a_idx'),
        ),
        migrations.AddIndex(
            model_name='exportattempt',
            index=models.Index(fields=['status'], name='invoices_ex_status_54910d_idx'),
        ),
        migrations.AddIndex(
            model_name='exportattempt',
            index=models.Index(fields=['created_at'], name='invoices_ex_created_21cb7c_idx'),
        ),
        migrations.AddConstraint(
            model_name='exportattempt',
            constraint=models.UniqueConstraint(fields=('export_record', 'attempt_no'), name='uniq_export_attempt_no'),
        ),
        migrations.AddIndex(
            model_name='finalinvoice',
            index=models.Index(fields=['drf'], name='invoices_fi_drf_c22ab1_idx'),
        ),
        migrations.AddIndex(
            model_name='finalinvoice',
            index=models.Index(fields=['status'], name='invoices_fi_status_dda894_idx'),
        ),
        migrations.AddIndex(
            model_name='finalinvoice',
            index=models.Index(fields=['export_status'], name='invoices_fi_export__f678bc_idx'),
        ),
        migrations.AddIndex(
            model_name='finalinvoice',
            index=models.Index(fields=['transaction_date'], name='invoices_fi_transac_2d78b8_idx'),
        ),
        migrations.AddIndex(
            model_name='finalinvoice',
            index=models.Index(fields=['created_at'], name='invoices_fi_created_005c09_idx'),
        ),
        migrations.AddIndex(
            model_name='finalinvoice',
            index=models.Index(fields=['department'], name='invoices_fi_departm_72fe57_idx'),
        ),
        migrations.AddIndex(
            model_name='finalinvoice',
            index=models.Index(fields=['counterparty'], name='invoices_fi_counter_3a5acf_idx'),
        ),
        migrations.AddIndex(
            model_name='exportrecord',
            index=models.Index(fields=['status'], name='invoices_ex_status_64a504_idx'),
        ),
        migrations.AddIndex(
            model_name='exportrecord',
            index=models.Index(fields=['created_at'], name='invoices_ex_created_c7ee1b_idx'),
        ),
        migrations.AddIndex(
            model_name='exportrecord',
            index=models.Index(fields=['updated_at'], name='invoices_ex_updated_a69f6d_idx'),
        ),
        migrations.AddConstraint(
            model_name='finalinvoiceline',
            constraint=models.UniqueConstraint(fields=('final_invoice', 'line_no'), name='uniq_final_line_no'),
        ),
        migrations.AddIndex(
            model_name='invoicefieldchangehistory',
            index=models.Index(fields=['field_name'], name='invoices_in_field_n_6330ab_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicefieldchangehistory',
            index=models.Index(fields=['created_at'], name='invoices_in_created_6bd27e_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicenumbersequence',
            index=models.Index(fields=['sequence_date'], name='invoices_in_sequenc_078be6_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicenumbersequence',
            index=models.Index(fields=['department', 'sequence_date'], name='invoices_in_departm_e3ff68_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoicenumbersequence',
            constraint=models.UniqueConstraint(fields=('department', 'sequence_date', 'version'), name='uniq_department_sequence_daily'),
        ),
        migrations.AddIndex(
            model_name='invoicestatushistory',
            index=models.Index(fields=['created_at'], name='invoices_in_created_f78fa6_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicestatushistory',
            index=models.Index(fields=['to_status'], name='invoices_in_to_stat_c26e10_idx'),
        ),
        migrations.AddIndex(
            model_name='materializationjob',
            index=models.Index(fields=['status'], name='invoices_ma_status_38febb_idx'),
        ),
        migrations.AddIndex(
            model_name='materializationjob',
            index=models.Index(fields=['created_at'], name='invoices_ma_created_b50dff_idx'),
        ),
        migrations.AddIndex(
            model_name='rawtransaction',
            index=models.Index(fields=['drf'], name='invoices_ra_drf_6284db_idx'),
        ),
        migrations.AddIndex(
            model_name='rawtransaction',
            index=models.Index(fields=['status'], name='invoices_ra_status_fe5183_idx'),
        ),
        migrations.AddIndex(
            model_name='rawtransaction',
            index=models.Index(fields=['transaction_date'], name='invoices_ra_transac_e76cd6_idx'),
        ),
        migrations.AddIndex(
            model_name='rawtransaction',
            index=models.Index(fields=['created_at'], name='invoices_ra_created_ae2b3b_idx'),
        ),
        migrations.AddIndex(
            model_name='rawtransaction',
            index=models.Index(fields=['received_at'], name='invoices_ra_receive_faa2eb_idx'),
        ),
        migrations.AddIndex(
            model_name='rawtransaction',
            index=models.Index(fields=['payload_hash'], name='invoices_ra_payload_3f2425_idx'),
        ),
        migrations.AddIndex(
            model_name='rawtransaction',
            index=models.Index(fields=['counterparty'], name='invoices_ra_counter_b38733_idx'),
        ),
        migrations.AddIndex(
            model_name='rawtransaction',
            index=models.Index(fields=['department'], name='invoices_ra_departm_9ea5b8_idx'),
        ),
        migrations.AddIndex(
            model_name='processingerror',
            index=models.Index(fields=['stage'], name='invoices_pr_stage_19a670_idx'),
        ),
        migrations.AddIndex(
            model_name='processingerror',
            index=models.Index(fields=['created_at'], name='invoices_pr_created_7d16b8_idx'),
        ),
        migrations.AddIndex(
            model_name='processingerror',
            index=models.Index(fields=['resolved'], name='invoices_pr_resolve_d39e8b_idx'),
        ),
        migrations.AddIndex(
            model_name='idempotencyrecord',
            index=models.Index(fields=['payload_hash'], name='invoices_id_payload_8c96b2_idx'),
        ),
        migrations.AddIndex(
            model_name='idempotencyrecord',
            index=models.Index(fields=['drf'], name='invoices_id_drf_b12d2d_idx'),
        ),
        migrations.AddIndex(
            model_name='idempotencyrecord',
            index=models.Index(fields=['first_seen_at'], name='invoices_id_first_s_07afcc_idx'),
        ),
        migrations.AddConstraint(
            model_name='draftinvoiceline',
            constraint=models.UniqueConstraint(fields=('draft_invoice', 'line_no'), name='uniq_draft_line_no'),
        ),
    ]
