# Generated by Django 5.2.6 on 2026-04-22 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='materializationjob',
            name='invoices_ma_created_b50dff_idx',
        ),
        migrations.RemoveIndex(
            model_name='rawtransaction',
            name='invoices_ra_created_ae2b3b_idx',
        ),
        migrations.RemoveField(
            model_name='materializationjob',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='rawtransaction',
            name='created_at',
        ),
        migrations.AddField(
            model_name='rawtransaction',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='invoices.finalinvoice'),
        ),
        migrations.AddIndex(
            model_name='materializationjob',
            index=models.Index(fields=['started_at'], name='invoices_ma_started_cb9789_idx'),
        ),
        migrations.AddIndex(
            model_name='rawtransaction',
            index=models.Index(fields=['invoice'], name='invoices_ra_invoice_af74e0_idx'),
        ),
    ]
