# Generated by Django 5.2.6 on 2026-04-22 16:56

from django.db import migrations, models


def migrate_status_values(apps, schema_editor):
    del schema_editor
    DraftInvoice = apps.get_model("invoices", "DraftInvoice")
    FinalInvoice = apps.get_model("invoices", "FinalInvoice")
    InvoiceStatusHistory = apps.get_model("invoices", "InvoiceStatusHistory")

    draft_map = {
        "DRAFT": "project_created",
        "READY": "project_created",
        "MATERIALIZED": "project_created",
        "MATERIALIZATION_ERROR": "validating_error",
        "VALIDATION_ERROR": "validating_error",
    }
    for old_value, new_value in draft_map.items():
        DraftInvoice.objects.filter(status=old_value).update(status=new_value)

    final_map = {
        "MATERIALIZED": "invoice_created",
        "EXPORT_READY": "invoice_created",
        "EXPORT_ERROR": "sending_error",
        "RETRY_PENDING": "sending_error",
        "SENT": "sent",
    }
    for old_value, new_value in final_map.items():
        FinalInvoice.objects.filter(status=old_value).update(status=new_value)
        FinalInvoice.objects.filter(export_status=old_value).update(export_status=new_value)
        InvoiceStatusHistory.objects.filter(from_status=old_value).update(from_status=new_value)
        InvoiceStatusHistory.objects.filter(to_status=old_value).update(to_status=new_value)


def noop_reverse(apps, schema_editor):
    del apps, schema_editor


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_remove_materializationjob_invoices_ma_created_b50dff_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftinvoice',
            name='status',
            field=models.CharField(choices=[('project_created', 'Project created'), ('validating_error', 'Validating error')], default='project_created', max_length=32),
        ),
        migrations.AlterField(
            model_name='finalinvoice',
            name='export_status',
            field=models.CharField(choices=[('invoice_created', 'Invoice created'), ('sending_error', 'Sending error'), ('sent', 'Sent')], default='invoice_created', max_length=32),
        ),
        migrations.AlterField(
            model_name='finalinvoice',
            name='status',
            field=models.CharField(choices=[('invoice_created', 'Invoice created'), ('sending_error', 'Sending error'), ('sent', 'Sent')], default='invoice_created', max_length=32),
        ),
        migrations.RunPython(migrate_status_values, noop_reverse),
    ]
