# Generated by Django 5.2.6 on 2026-04-22 17:43

import uuid
from django.db import migrations, models


def populate_public_ids(apps, schema_editor):
    del schema_editor
    Department = apps.get_model("invoices", "Department")
    Counterparty = apps.get_model("invoices", "Counterparty")

    for department in Department.objects.filter(public_id__isnull=True):
        department.public_id = uuid.uuid4()
        department.save(update_fields=["public_id"])

    for counterparty in Counterparty.objects.filter(public_id__isnull=True):
        counterparty.public_id = uuid.uuid4()
        counterparty.save(update_fields=["public_id"])


def noop_reverse(apps, schema_editor):
    del apps, schema_editor


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_draftinvoice_status_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='finalinvoice',
            name='invoices_fi_transac_2d78b8_idx',
        ),
        migrations.RenameField(
            model_name='finalinvoice',
            old_name='transaction_date',
            new_name='issue_date',
        ),
        migrations.RenameField(
            model_name='finalinvoice',
            old_name='invoice_number',
            new_name='number',
        ),
        migrations.AddField(
            model_name='counterparty',
            name='public_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='public_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(populate_public_ids, noop_reverse),
        migrations.AlterField(
            model_name='counterparty',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='finalinvoice',
            name='payment_doc_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalinvoice',
            name='payment_doc_number',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='rawtransaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='rawtransaction',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawtransaction',
            name='credit_account',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawtransaction',
            name='debit_account',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rawtransaction',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawtransaction',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='rawtransaction',
            name='unit_measure',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='rawtransaction',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='rawtransaction',
            name='vat_amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='rawtransaction',
            name='vat_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddIndex(
            model_name='finalinvoice',
            index=models.Index(fields=['issue_date'], name='invoices_fi_issue_d_d2636d_idx'),
        ),
        migrations.AddIndex(
            model_name='rawtransaction',
            index=models.Index(fields=['created_at'], name='invoices_ra_created_ae2b3b_idx'),
        ),
    ]
