# Generated by Django 5.2.6 on 2026-04-23 04:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def _create_numeric_uuid_casts(apps, schema_editor):
    del apps
    if schema_editor.connection.vendor != "postgresql":
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            CREATE OR REPLACE FUNCTION int4_to_uuid(integer)
            RETURNS uuid
            LANGUAGE SQL
            IMMUTABLE
            STRICT
            AS 'SELECT md5($1::text)::uuid';
            """
        )
        cursor.execute(
            """
            CREATE OR REPLACE FUNCTION int8_to_uuid(bigint)
            RETURNS uuid
            LANGUAGE SQL
            IMMUTABLE
            STRICT
            AS 'SELECT md5($1::text)::uuid';
            """
        )
        cursor.execute(
            """
            DO $$
            BEGIN
              IF NOT EXISTS (
                SELECT 1
                FROM pg_cast c
                JOIN pg_type s ON s.oid = c.castsource
                JOIN pg_type t ON t.oid = c.casttarget
                WHERE s.typname = 'int4' AND t.typname = 'uuid'
              ) THEN
                CREATE CAST (integer AS uuid) WITH FUNCTION int4_to_uuid(integer);
              END IF;
            END $$;
            """
        )
        cursor.execute(
            """
            DO $$
            BEGIN
              IF NOT EXISTS (
                SELECT 1
                FROM pg_cast c
                JOIN pg_type s ON s.oid = c.castsource
                JOIN pg_type t ON t.oid = c.casttarget
                WHERE s.typname = 'int8' AND t.typname = 'uuid'
              ) THEN
                CREATE CAST (bigint AS uuid) WITH FUNCTION int8_to_uuid(bigint);
              END IF;
            END $$;
            """
        )


def _drop_numeric_uuid_casts(apps, schema_editor):
    del apps
    if schema_editor.connection.vendor != "postgresql":
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DROP CAST IF EXISTS (bigint AS uuid);")
        cursor.execute("DROP CAST IF EXISTS (integer AS uuid);")
        cursor.execute("DROP FUNCTION IF EXISTS int8_to_uuid(bigint);")
        cursor.execute("DROP FUNCTION IF EXISTS int4_to_uuid(integer);")


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_draftinvoice_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='finalinvoiceline',
            name='uniq_final_line_no',
        ),
        migrations.RemoveIndex(
            model_name='finalinvoice',
            name='invoices_fi_drf_c22ab1_idx',
        ),
        migrations.RemoveIndex(
            model_name='finalinvoice',
            name='invoices_fi_export__f678bc_idx',
        ),
        migrations.RemoveIndex(
            model_name='finalinvoice',
            name='invoices_fi_transac_2d78b8_idx',
        ),
        migrations.RemoveIndex(
            model_name='rawtransaction',
            name='invoices_ra_transac_e76cd6_idx',
        ),
        migrations.RenameField(
            model_name='finalinvoice',
            old_name='transaction_date',
            new_name='issue_date',
        ),
        migrations.RenameField(
            model_name='finalinvoice',
            old_name='invoice_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='rawtransaction',
            old_name='transaction_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='rawtransaction',
            old_name='transaction_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='counterparty',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='counterparty',
            name='kpp',
        ),
        migrations.RemoveField(
            model_name='department',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='departmentaccess',
            name='role',
        ),
        migrations.RemoveField(
            model_name='finalinvoice',
            name='drf',
        ),
        migrations.RemoveField(
            model_name='finalinvoice',
            name='export_status',
        ),
        migrations.RemoveField(
            model_name='finalinvoice',
            name='materialized_at',
        ),
        migrations.RemoveField(
            model_name='finalinvoiceline',
            name='line_no',
        ),
        migrations.AddField(
            model_name='counterparty',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='finalinvoice',
            name='current_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='finalinvoice',
            name='last_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_authored_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finalinvoice',
            name='payment_doc_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalinvoice',
            name='payment_doc_number',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='finalinvoice',
            name='sequence_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='rawtransaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='rawtransaction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawtransaction',
            name='credit_account',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawtransaction',
            name='debit_account',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.RunPython(_create_numeric_uuid_casts, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='counterparty',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, default='', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='finalinvoice',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='finalinvoice',
            name='status',
            field=models.CharField(choices=[('project_created', 'Project created'), ('validating_error', 'Validating error'), ('invoice_created', 'Invoice created'), ('sending_error', 'Sending error'), ('sent', 'Sent')], default='project_created', max_length=32),
        ),
        migrations.AlterField(
            model_name='finalinvoiceline',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rawtransaction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rawtransaction',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawtransaction',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='rawtransaction',
            name='unit_measure',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='rawtransaction',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='rawtransaction',
            name='vat_amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='rawtransaction',
            name='vat_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddIndex(
            model_name='finalinvoice',
            index=models.Index(fields=['issue_date'], name='invoices_fi_issue_d_d2636d_idx'),
        ),
        migrations.AddIndex(
            model_name='rawtransaction',
            index=models.Index(fields=['date'], name='invoices_ra_date_ae2350_idx'),
        ),
        migrations.AddIndex(
            model_name='rawtransaction',
            index=models.Index(fields=['created_at'], name='invoices_ra_created_ae2b3b_idx'),
        ),
        migrations.AddField(
            model_name='invoiceversion',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoiceversion',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='invoices.finalinvoice'),
        ),
        migrations.AddConstraint(
            model_name='invoiceversion',
            constraint=models.UniqueConstraint(fields=('invoice', 'version_number'), name='uniq_invoice_version_number'),
        ),
        migrations.RunPython(_drop_numeric_uuid_casts, migrations.RunPython.noop),
    ]
