# Generated by Django 5.2.6 on 2026-04-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(choices=[("admin", "Admin"), ("user", "User")], max_length=32),
        ),
        migrations.AddField(
            model_name="user",
            name="departments",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                through="invoices.DepartmentAccess",
                to="invoices.department",
            ),
        ),
    ]
